# This file contains our custom configurations for the kube-prometheus-stack Helm chart.
# We will keep this minimal and only override the defaults we need to change.

# --- Grafana Configuration ---
grafana:
  # Set a default password for the 'admin' user.
  # In a production environment, it's better to manage this secret separately.
  adminPassword: "Password@123"

  # Change the service type to NodePort to expose Grafana externally.
  service:
    type: NodePort
    # We can set a static port for predictability. This must be in the 30000-32767 range.
    nodePort: 32000

  # Persist the Grafana database and dashboards.
  # This requires a default StorageClass to be available in your cluster.
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    accessModes:
      - ReadWriteOnce

# --- Prometheus Configuration ---
prometheus:
  prometheusSpec:
    # Persist the Prometheus time-series database.
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard # Make sure this matches a StorageClass in your cluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi


