# This file contains our custom configurations for the kube-prometheus-stack Helm chart.
# We will keep this minimal and only override the defaults we need to change.

# --- Grafana Configuration ---
grafana:
  # Set a default password for the 'admin' user.
  adminPassword: "Password@123"

  service:
    type: NodePort
    nodePort: 32000

  ingress:
    enabled: false

  # Persistence for Grafana is disabled.
  persistence:
    enabled: false

# --- Prometheus Configuration ---
prometheus:
  prometheusSpec:
    # We are disabling persistence for Prometheus for now to resolve the "Pending" pod issue.
    # Setting storageSpec to an empty object tells Helm to use a temporary 'emptyDir' volume.
    storageSpec: {}

# --- Alertmanager Configuration ---
alertmanager:
  alertmanagerSpec:
    # We are also disabling persistence for Alertmanager.
    storage: {}


