apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: willchrist/product-service:491b1f4
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: ecommerce-config
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
  template:
    spec:
      containers:
        - image: willchrist/product-service:491b1f4
