apiVersion: v1
kind: Service
metadata:
  name: query-service
  labels:
    app: query-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

