apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
  labels:
    app: cart-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- if .Values.persistence.enabled }}
      initContainers:
      - name: init-permissions
        image: {{ .Values.initContainer.image }}
        securityContext:
          runAsUser: {{ .Values.initContainer.runAsUser }}
        command: {{ .Values.initContainer.command }}
        volumeMounts:
        - name: cart-storage
          mountPath: {{ .Values.persistence.mountPath }}
      {{- end }}
      containers:
        - name: cart-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:sqlite:{{ .Values.persistence.mountPath }}/cart.db"
          volumeMounts:
            - name: cart-storage
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: cart-storage
          persistentVolumeClaim:
            claimName: cart-db-pvc

   
