replicaCount: 1

image:
  repository: willchrist/front
  tag: beta
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  configMapName: ecommerce-config

