apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-db-pvc # The name we'll use to refer to this storage claim.
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 1Gi # Request 1 Gibibyte of storage.
  template:
    spec:
      containers:
        - image: willchrist/cart-service:efac7f0
