replicaCount: 1

image:
  repository: willchrist/query
  tag: beta
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8002

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

env:
  portProduct: "8001"
  queryServicePort: "8002"
  productServicePort: "8001"
  awsAccessKeyId: "DUMMY_AWS_ACCESS_KEY_ID"
  awsSecretAccessKey: "DUMMY_AWS_SECRET_ACCESS_KEY"
  awsRegion: "us-east-1"

startupProbe:
  path: /query?q=startup
  port: 8002
  failureThreshold: 12
  periodSeconds: 10
  timeoutSeconds: 10

