name: Provision + Run master-setup (Option 2)

on:
  workflow_dispatch:

jobs:
  provision-and-remote-setup:
    runs-on: ubuntu-latest
    env:
      TF_WORKDIR: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init & Apply
        working-directory: ${{ env.TF_WORKDIR }}
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="runner_token=${{ secrets.RUNNER_TOKEN }}" \
            -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Get EC2 public IP
        id: ip
        working-directory: ${{ env.TF_WORKDIR }}
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Wait for SSH
        run: |
          HOST="${{ env.EC2_PUBLIC_IP }}"
          for i in {1..30}; do
            ssh -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/deploy_key ubuntu@"$HOST" "echo ok" >/dev/null 2>&1 && break
            echo "Waiting for SSH... attempt $i"
            sleep 10
          done

      - name: Run master-setup.sh remotely
        run: |
          HOST="${{ env.EC2_PUBLIC_IP }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ubuntu@"$HOST" /bin/bash <<'EOF'
set -euo pipefail

if [ ! -d /home/ubuntu/deploy-centre ]; then
git clone https://github.com/shopping-microservices-microshop/deploy-centre.git /home/ubuntu/deploy-centre
chown -R ubuntu:ubuntu /home/ubuntu/deploy-centre
fi

cd /home/ubuntu/deploy-centre
chmod +x master-setup.sh
sudo -u ubuntu ./master-setup.sh "${RUNNER_TOKEN}" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
EOF
        env:
          RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Post-setup info
        run: |
          echo "✅ master-setup.sh has been triggered on the EC2 instance."
          echo "ssh -i <your-key.pem> ubuntu@${{ env.EC2_PUBLIC_IP }}"
